Comment log br
dnplkv/hw5_Polyakov pull request #5
Opened 2021-04-12 17:51 UTC by dnplkv

Hopefully fixed issues with comments and middleware

2021-04-12 19:59 UTC, romanitalian requested changes
Нужно поправить LogMiddleware.

2021-04-12 19:59 UTC, romanitalian commented on blog/main/middlewares.py
> +        ip_address = Log(ip_address=ip)
1. Получение IP вынести в отдельную функцию. Плюс не вижу проверку на наличие HTTP_X_REAL_IP.
2. Log save() - вызывать единажды. Сейчас это три места, где идёт сохранение: 
- path.save()
- log.save()
-  ip_address.save()
3. Задание переменных для простановки полей в модель Log - вынести выше. То есть сначала подготовить utm, path, ip, time_exec. А проставить поля для Log. И следом сохранить Log.

2021-04-14 11:25 UTC, romanitalian approved these changes
Можно мержить в main.
Пересдавать задачу не нужно.
По правилам - за пересдачу нужно снижать балл(

2021-04-14 11:25 UTC, romanitalian commented on blog/main/middlewares.py
> +            logger.save()
Один раз logger.save()
```
    def __call__(self, request):
        response = self.get_response(request)

        st = time()
        path = request.path
        user_ip = get_ip_adress(request)
        utm = request.GET.get('utm')
        time_ex = time() - st
        if user_ip && utm:
             logger = Log(utm=str(utm), time_exec=time_ex, user_ip=user_ip, path=path)
             logger.save()
   
```

2021-04-14 11:29 UTC, dnplkv commented
Спасибо что проверили. Ничего страшного - баллы не главное, для меня важнее "набивание шишек" и усвоение материала😄

2021-04-14 11:30 UTC, merged